server:
  port: 8084

spring:
  application:
    name: behavior-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  charset:
    console: UTF-8
    file: UTF-8