server.port=8082

spring.application.name=order-service

#### PostgreSQL ####
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#### Spring Data JPA ####
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#### Axon ####
axon.eventhandling.processors.order-group.mode=tracking
axon.eventhandling.processors.order-group.initial-segment-count=1
axon.axonserver.servers=127.0.0.1:8124
axon.axonserver.context=default
axon.axonserver.component-name=order-service

# \u5F37\u5236 Axon \u4F7F\u7528 jackson \u8655\u7406\u6240\u6709\u5E8F\u5217\u5316
axon.serializer.general=jackson
axon.serializer.messages=jackson
axon.serializer.events=jackson


logging.charset.console=UTF-8
logging.charset.file=UTF-8